### ISSUE TITLE
"Cannot perform redirects after login, no parameters fetched"

### ISSUE THREAD

**Issue by sofauxboho** [pyscsd/steamCloudSaveDownloader#10]
scsd had been running smoothly via the docker container for several months but started failing and throwing an error as of 11:30pm PDT on 10/13/24:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 122, in __main__
    main(parsed_args, notifier_)
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 280, in main
    auth_.refresh_session()
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/auth.py", line 108, in refresh_session
    self.login_executor._perform_redirects(finalized_response.json())
  File "/usr/lib/python3.10/site-packages/steampy/login.py", line 110, in _perform_redirects
    raise Exception('Cannot perform redirects after login, no parameters fetched')
Exception: Cannot perform redirects after login, no parameters fetched
```

I tried reauthenticating and running it manually for the heck of it, and now get a slightly different traceback:
```
root@TVWorld:~# docker exec -it scsd scsd
2024-10-14 21:23:31 [INFO] Config file not provided
2024-10-14 21:23:31 [WARNING] Detect container environment. Please run scsd with `/opt/run.sh` and authentication with `scsd_auth`
2024-10-14 21:23:31 [INFO] Options: {'General': {'save_dir': './data', '2fa': 'mobile'}, 'Rotation': {'rotation': 15}, 'Log': {'log_level': 2}, 'Notifier': {'notify_if_no_change': False, 'notifier': '', 'webhook': '', 'path': '', 'level': 1}, 'Target': {'mode': '', 'list': []}, 'Danger Zone': {'wait_interval': [3, 5]}, 'auth': None}
2024-10-14 21:23:31 [INFO] CWD: /
2024-10-14 21:23:31 [INFO] Files will be saved to './data'
2024-10-14 21:23:31 [INFO] Refreshing session
2024-10-14 21:23:38 [ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x14f58fa33ee0>: Failed to resolve 'steam.tv' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='steam.tv', port=443): Max retries exceeded with url: /login/settoken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x14f58fa33ee0>: Failed to resolve 'steam.tv' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 122, in __main__
    main(parsed_args, notifier_)
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 280, in main
    auth_.refresh_session()
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/auth.py", line 108, in refresh_session
    self.login_executor._perform_redirects(finalized_response.json())
  File "/usr/lib/python3.10/site-packages/steampy/login.py", line 113, in _perform_redirects
    self.session.post(pass_data['url'], pass_data['params'])
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='steam.tv', port=443): Max retries exceeded with url: /login/settoken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x14f58fa33ee0>: Failed to resolve 'steam.tv' ([Errno -3] Try again)"))
```

**Comment by hhhhhojeihsu** [comment]
Seems like the access token is out of date. Could you make sure you re authenticate with the command `docker exec -it scsd scsd_auth <username>`.

**Comment by sofauxboho** [comment]
Yup, I ran `docker exec -it scsd scsd_auth <username>` and then immediately after ran `docker exec -it scsd scsd`. The result was the error message shown in the second code block above.

However, I have not received any additional error messages through the discord notifier since then. Looking at the log it does appear to be running successfully when running as scheduled by the docker image. 

I have just re-added `notify_if_no_change = true` to scsd.conf and will keep an eye on it for the next little bit. Will report back if anything else goes wrong, but this can be closed if you'd like.

**Comment by sofauxboho** [comment]
Yup, now getting correct `[scsd-0.0.76] :white_check_mark:  No changes` messages in discord. Closing this out.
