### ISSUE TITLE
No finished notification on Discord (Errors work)

### ISSUE THREAD

**Issue by FilGoodInc** [pyscsd/steamCloudSaveDownloader#5]
Hi!

First, thank you so much for the tool, it's very useful!
One of the features I really like is the Notifications since I let the thing automatically run once a month.

### Problem:
Only Errors are sent to Discord, nothing when the download is finished.

Error logs showing that the config is correctly configured:
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/23322177/ffb5cee2-75e2-4e20-8064-ddc7cab5973e)

Sadly there's no confirmation when the scsd docker command is finished.
There's also no Error Logs (Debug Level), only Info

I'm not sure if I don't understand the Notifier description or it's an actual bug:
> Description: How to notify when scsd finish or encounter error. Supported method

### Infos
- OS: TrueNAS-SCALE-22.12.4.2 (Linux)
- Using Docker Container
- Env Variables: 
    - CRON_VAR=0 12 19 */1 *
    - Nothing else
- Full execution log:
[scsd.log](https://github.com/pyscsd/steamCloudSaveDownloader/files/15032359/scsd.log)

<details>
  <summary>Config - Click to expand...</summary>

````
#https://github.com/pyscsd/steamCloudSaveDownloader/wiki/Config-File
[General]
save_dir = ./data
2fa = mobile

[Log]
log_level = 3

[Rotation]
rotation = 15

[Notifier]
notifier = discord
webhook = https://discord.com/api/webhooks/**censored-but-contains-valid-webhook**
notify_if_no_change = true
level = 3

[Target]
#steam app_id filter (include/exclude)
mode = exclude
#comma separated list
list = 
````
</details>
<details>
  <summary>Container settings (Doubt they are going to be useful though) - Click to expand...</summary>
  <img src="https://github.com/pyscsd/steamCloudSaveDownloader/assets/23322177/ad5ecfe8-2a1c-4b8b-af9d-02072e4eb204">
</details>

**Comment by hhhhhojeihsu** [comment]
Hi

Thank you for the kind words. 😄 

Seems like the config is not loaded by the program. Could you show me what does the `/config` looks like within the container. With the ownership of those files? Thanks.

**Comment by FilGoodInc** [comment]
Here's the top level of the container containing` /config` (Belongs to user) and the scsd.conf file inside it as well.
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/23322177/32ea8073-9050-4c99-baa1-0ee9068c61be)

**Comment by hhhhhojeihsu** [comment]
Seems the config is in the right place and I don' think the timezone would make a difference. Could you do me a favor and provide these additional information?

1. How did you trigger the program. Via periodic job(crontab) or invoke the program manually? If you want to run it manually. Either run `/bin/sh /opt/run.sh` or `scsd -f /config/scsd.conf` to get the correct config file.
2. Could you provide the output log of the container itself.

**Comment by FilGoodInc** [comment]
1. I invoked manually (I plan running the cron job aswell however)
````
WARNING: Your user does not have sudo privileges so /usr/local/bin/k3s command will run
on your behalf. This might cause permission issues.
/ # scsd -f /config/scsd.conf
2024-04-19 16:51:51 [INFO] scsd-0.0.70 started
2024-04-19 16:51:51 [DEBUG] {'General': {'save_dir': './data', '2fa': 'mobile'}, 'Rotation': {'rotation': 15}, 'Log': {'log_level': 3}, 'Notifier': {'notify_if_no_change': True, 'notifier': 'discord', 'webhook': 'https://discord.com/api/webhooks/**censored-but-contains-valid-webhook**', 'path': '', 'level': 3}, 'Target': {'mode': 'exclude', 'list': None}, 'Danger Zone': {'wait_interval': [3, 5]}}
2024-04-19 16:51:51 [INFO] Files will be saved to './data'
2024-04-19 16:51:51 [INFO] Refreshing session
2024-04-19 16:51:53 [INFO] Getting Game Save List
2024-04-19 16:51:53 [INFO] Random sleep for 5 seconds
Webhook status code 405: {"message": "405: Method Not Allowed", "code": 0}
2024-04-19 16:51:59 [ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 93, in __main__
    main(parsed_args, notifier_)
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 257, in main
    target_count = get_overall_target_counts(parsed_args['Target'], game_list)
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 66, in get_overall_target_counts
    return len([game for game in p_game_list if should_process_appid(p_target, game['app_id'])])
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 66, in <listcomp>
    return len([game for game in p_game_list if should_process_appid(p_target, game['app_id'])])
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 61, in should_process_appid
    return p_input not in p_target['list']
TypeError: argument of type 'NoneType' is not iterable

````

**Comment by FilGoodInc** [comment]
1. Manually running (But I plan on using the cron job)
`/bin/sh /opt/run.sh` seems to work (I received a Discord notification saying [checkmark] No Changes
````
/ # /bin/sh /opt/run.sh
[run.sh] Config specified /config/scsd.conf
2024-04-19 17:04:49 [INFO] Config read from '/config/scsd.conf'
2024-04-19 17:04:49 [INFO] Options: {'General': {'save_dir': './data', '2fa': 'mobile'}, 'Rotation': {'rotation': 15}, 'Log': {'log_level': 3}, 'Notifier': {'notify_if_no_change': True, 'notifier': 'discord', 'webhook': 'https://discord.com/api/webhooks/1230653096409956412/Jm-2rJ6FDEhtsvsLAnzQ1XEZICQ2mmkp6PZz5pGMNOOD9zllvlM_KsOXqqDwlXvG7bKm', 'path': '', 'level': 3}, 'Target': {'mode': 'exclude', 'list': None}, 'Danger Zone': {'wait_interval': [3, 5]}}
2024-04-19 17:04:49 [INFO] CWD: /
2024-04-19 17:04:49 [INFO] Files will be saved to './data'
2024-04-19 17:04:49 [INFO] Refreshing session
2024-04-19 17:04:50 [INFO] Getting Game Save List
2024-04-19 17:04:50 [INFO] Random sleep for 5 seconds
/ # 
````
However `scsd -f /config/scsd.conf` doesn't work.
````
/ # scsd -f /config/scsd.conf
2024-04-19 17:03:17 [INFO] Config read from '/config/scsd.conf'
2024-04-19 17:03:17 [INFO] Options: {'General': {'save_dir': './data', '2fa': 'mobile'}, 'Rotation': {'rotation': 15}, 'Log': {'log_level': 3}, 'Notifier': {'notify_if_no_change': True, 'notifier': 'discord', 'webhook': 'https://discord.com/api/webhooks/1230653096409956412/Jm-2rJ6FDEhtsvsLAnzQ1XEZICQ2mmkp6PZz5pGMNOOD9zllvlM_KsOXqqDwlXvG7bKm', 'path': '', 'level': 3}, 'Target': {'mode': 'exclude', 'list': None}, 'Danger Zone': {'wait_interval': [3, 5]}}
2024-04-19 17:03:17 [INFO] CWD: /
2024-04-19 17:03:17 [INFO] Files will be saved to './data'
2024-04-19 17:03:17 [INFO] Refreshing session
2024-04-19 17:03:19 [INFO] Getting Game Save List
2024-04-19 17:03:19 [INFO] Random sleep for 3 seconds
2024-04-19 17:03:23 [ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 117, in __main__
    main(parsed_args, notifier_)
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 286, in main
    target_count = get_overall_target_counts(parsed_args['Target'], game_list)
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 88, in get_overall_target_counts
    return len([game for game in p_game_list if should_process_appid(p_target, game['app_id'])])
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 88, in <listcomp>
    return len([game for game in p_game_list if should_process_appid(p_target, game['app_id'])])
  File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 83, in should_process_appid
    return p_input not in p_target['list']
TypeError: argument of type 'NoneType' is not iterable
````

2. Container output log
[steam-cloud-save-downloader_steam-cloud-save-downloader-ix-chart-547b94c988-wld9r_ix-chart.log](https://github.com/pyscsd/steamCloudSaveDownloader/files/15043493/steam-cloud-save-downloader_steam-cloud-save-downloader-ix-chart-547b94c988-wld9r_ix-chart.log)

*Note the container is updated to your new v0.0.71 release

**Comment by FilGoodInc** [comment]
Hmm, now both commands give the same error. Not sure what I did to make it work that one time 😅

**Comment by FilGoodInc** [comment]
Okay, I came back to it after work and I found an issue:
I had an empty Target Exclude List in the config
````
[Target]
mode = exclude
list = 
````
I just added a 7 and the problem was fixed. (Skipping Steam Client [AppId](https://steamdb.info/app/7/info/)
I had to remove the key value pair completely to have an empty list. (that's fine by me)

Past that problem now.
When I manually enter `scsd -f /config/scsd.conf`, it works fine and notifies as expected.

---

Now I have permission problems when trying to authenticate. Looking into it right now.
````
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/23322177/bf2f78ae-b8ca-4442-b340-572e57eb8933)
````

**Comment by FilGoodInc** [comment]
Auto Cron Job also works.
Just had to change `save_dir = ./data` to `save_dir = /data`*

*Manual run work with both `./data` and '/data' but not the auto cron job.

For my case I'm happy with using `scsd -f /config/scsd.conf`.

But I think it still would be nice not to have to specify it everytime. 
Problem might stems for a similar reason why the cron didn't work with `./data`

**Comment by hhhhhojeihsu** [comment]
So based on your detailed descriptions. It's caused by the following issues:
1. Incorrectly specify the config file. You did not run `scsd` with `-f` option previously
2. Empty target list (a bug)
3. `/data` folder permission issue.
4. `./data` is different from `/data`. Because working directory is different for cron job (`/`) and running command (`/user`)

---
I will add more checking and info to prevent future users encounter these sorts of situation. So is this problem solved and did I miss anything.

**Comment by FilGoodInc** [comment]
You summarized all the issues very well. Most of them are definitely not bugs and just good things to know or enhancement ideas.

Thank you for your time. I will use this thing for as long as I use Steam!
